name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/whats-the-time
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - run: ./scripts/build-minute-wheel.sh
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
